### ISSUE TITLE
indigo release?

### ISSUE THREAD

**Issue by vonovak** [strands-project/data_compression#62] opened 2015-02-24 10:53 UTC
Hello, could this package be released for indigo?
Thanks you

ping: @marc-hanheide

**Comment by marc-hanheide** [comment] 2015-02-24 11:38
isn't it yet? @nilsbore ?

**Comment by nilsbore** [comment] 2015-02-24 12:30
No, can I just release it by choosing ros_distro indigo here: https://lcas.lincoln.ac.uk/jenkins/view/Management/job/prepare-release/build?delay=0sec ?

**Comment by marc-hanheide** [comment] 2015-02-24 12:40
no... not if it has not been released before. I shall do it. Has it been tested on indigo?

**Comment by nilsbore** [comment] 2015-02-24 13:01
No, I'll test it tonight.

**Comment by nilsbore** [comment] 2015-02-24 13:04
@vonovak The `catkinized_libav` is something of a hack. If you want to compile it in a normal catkin workspace you need to remove `${LIBAV_COMPONENTS}` from this line https://github.com/strands-project/data_compression/blob/hydro-devel/catkinized_libav/CMakeLists.txt#L17 . Otherwise you need to first build `catkinized_libav` separately and then `libav_image_transport`. I tried to find a nice way of solving this but I haven't come across one yet.

**Comment by marc-hanheide** [comment] 2015-02-24 13:38
OK, trigger me here, when it's ready.

**Comment by nilsbore** [comment] 2015-02-24 21:59
I checked now and it compiled but I can't get my camera to work atm. I'll try with another camera in the lab tomorrow morning. Since image_transport is able to load the plugin I would say it's ok to release though, I can't see any reason for it not to work (appart from devel build complaints=P).

**Comment by marc-hanheide** [comment] 2015-02-25 10:35
I found that `libavdevice-dev`, `libavresample-dev`, `libavfilter-dev` need to be installed for `catkinized_libav` to compile. These are not listed in `package.xml`, are they?

**Comment by marc-hanheide** [comment] 2015-02-25 10:40
Some of this should be included via the rosdep `ffmpeg` key (see https://github.com/strands-project/rosdistro/blob/strands-devel/rosdep/base.yaml#L596), but I didn't find any rosdep key that imports exactly those libraries. Do I miss a think? Is this different to what it was in hydro? I believe so.

**Comment by marc-hanheide** [comment] 2015-02-25 10:46
I suggested to add a new rosdep key for this in https://github.com/strands-project/rosdistro/issues/370 @nilsbore please comment if that's something useful, please.

**Comment by marc-hanheide** [comment] 2015-02-25 11:00
#63 hopefully also takes care of the build order between catkinized_avlib and libav_image_transport...

**Comment by nilsbore** [comment] 2015-02-25 11:32
So the problem is not really that they are needed as dependencies. It might help with the warnings though. The problem is that the libraries are not present in the first pass of catkin (or cmake, not sure). If you don't list the libraries on https://github.com/strands-project/data_compression/blob/hydro-devel/catkinized_libav/CMakeLists.txt#L17, it will not check this in the pre-processing and the build will compile without any problems. However, for the package to export them properly (and for the compilation of `libav_image_transport` to work on the build server), you have to have those library export declarations in there. This time it will work because `catkinized_libav` will already have been installed and the libraries therefore actually present.

**Comment by nilsbore** [comment] 2015-02-25 11:33
So to be clear, the libraries that you specify as dependencies here are actually installed by `catkinized_libav`.

**Comment by marc-hanheide** [comment] 2015-02-25 14:22
fixed by #63 and release will be completed in about 30 minutes

**Closed as completed by marc-hanheide** 2015-02-25 14:22 UTC

**Comment by marc-hanheide** [comment] 2015-02-25 14:44
All released an tested. Works!

**Comment by nilsbore** [comment] 2015-02-25 14:52
Cool! Thanks for the help.
