### ISSUE TITLE
No depth recorded

### ISSUE THREAD

**Issue by cburbridge** [strands-project/data_compression#64] opened 2015-06-18 15:56 UTC
I am trying to record a bag file using

`roslaunch rosbag_openni_compression record.launch file:=/path/to/file.bag camera:=head_xtion`

It launches and outputs:

```
NODES
  /
    depth_compressor (image_transport/republish)
    recorder (rosbag/record)
    rgb_compressor (image_transport/republish)

ROS_MASTER_URI=http://bob:11311

core service [/rosout] found
process[depth_compressor-1]: started with pid [2566]
process[rgb_compressor-2]: started with pid [2571]
process[recorder-3]: started with pid [2576]
[ INFO] [1434642099.908496442]: Recording to /home/strands/test_rgbd_file.bag.
[ INFO] [1434642099.911241298]: Subscribing to /image_proc_head_xtion_rectify_mono/parameter_descriptions
[ INFO] [1434642099.920371009]: Subscribing to /rectify_depth_head_xtion/parameter_updates
[ INFO] [1434642099.927130821]: Subscribing to /image_proc_head_xtion_rectify_mono/parameter_updates
[ INFO] [1434642099.935951654]: Subscribing to /rectify_depth_head_xtion/parameter_descriptions
[ INFO] [1434642099.944202852]: Subscribing to /head_xtion/rgb/camera_info
[ INFO] [1434642099.952751981]: Subscribing to /image_proc_head_xtion_rectify_color/parameter_descriptions
[ INFO] [1434642099.961063612]: Subscribing to /rosout
[ INFO] [1434642099.969615944]: Subscribing to /image_proc_head_xtion_debayer/parameter_updates
[ INFO] [1434642099.979365094]: Subscribing to /rosout_agg
[ INFO] [1434642099.986902738]: Subscribing to /image_proc_head_xtion_debayer/parameter_descriptions
[ INFO] [1434642099.995034602]: Subscribing to /image_proc_head_xtion_rectify_color/parameter_updates
[ INFO] [1434642100.001341599]: Subscribing to /head_xtion/depth/camera_info
[ INFO] [1434642100.007597971]: Subscribing to /manager_head_xtion/bond
[ INFO] [1434642101.022842090]: Subscribing to /compressed_rgb/theora
[ INFO] [1434642101.035361454]: Subscribing to /compressed_rgb/theora/parameter_descriptions
[ INFO] [1434642101.042062744]: Subscribing to /compressed_rgb/theora/parameter_updates
```

but when I later play the bag, I can't get any pointclouds and get the message:

```
[ WARN] [1434641831.314939801, 1434641048.277004050]: [image_transport] Topics '/head_xtion/depth/image_raw' and '/head_xtion/depth/camera_info' do not appear to be synchronized. In the last 10s:
    Image messages received:      0
    CameraInfo messages received: 296
    Synchronized pairs:           0
```

rosbag info shows there are no compressed depth images in there:

```
strands@woody:~$ rosbag info test_rgbd_file.bag 
path:        test_rgbd_file.bag
version:     2.0
duration:    2:27s (147s)
start:       Jun 18 2015 16:23:56.71 (1434641036.71)
end:         Jun 18 2015 16:26:24.09 (1434641184.09)
size:        14.9 MB
messages:    14065
compression: none [20/20 chunks]
types:       bond/Status                           [eacc84bf5d65b6777d4c50f463dfb9c8]
             dynamic_reconfigure/Config            [958f16a05573709014982821e6822580]
             dynamic_reconfigure/ConfigDescription [757ce9d44ba8ddd801bb30bc456f946f]
             rosgraph_msgs/Log                     [acffd30cd6b6de30f120938c17c593fb]
             sensor_msgs/CameraInfo                [c9a58c1b0b154e0e6da7578cb991d214]
             theora_image_transport/Packet         [33ac4e14a7cff32e7e0d65f18bb410f3]
topics:      /compressed_rgb/theora                                        4366 msgs    : theora_image_transport/Packet        
             /compressed_rgb/theora/parameter_descriptions                    1 msg     : dynamic_reconfigure/ConfigDescription
             /compressed_rgb/theora/parameter_updates                         1 msg     : dynamic_reconfigure/Config           
             /head_xtion/depth/camera_info                                 4393 msgs    : sensor_msgs/CameraInfo               
             /head_xtion/rgb/camera_info                                   4392 msgs    : sensor_msgs/CameraInfo               
             /image_proc_head_xtion_debayer/parameter_descriptions            1 msg     : dynamic_reconfigure/ConfigDescription
             /image_proc_head_xtion_debayer/parameter_updates                 1 msg     : dynamic_reconfigure/Config           
             /image_proc_head_xtion_rectify_color/parameter_descriptions      1 msg     : dynamic_reconfigure/ConfigDescription
             /image_proc_head_xtion_rectify_color/parameter_updates           1 msg     : dynamic_reconfigure/Config           
             /image_proc_head_xtion_rectify_mono/parameter_descriptions       1 msg     : dynamic_reconfigure/ConfigDescription
             /image_proc_head_xtion_rectify_mono/parameter_updates            1 msg     : dynamic_reconfigure/Config           
             /manager_head_xtion/bond                                       883 msgs    : bond/Status                           (4 connections)
             /rectify_depth_head_xtion/parameter_descriptions                 1 msg     : dynamic_reconfigure/ConfigDescription
             /rectify_depth_head_xtion/parameter_updates                      1 msg     : dynamic_reconfigure/Config           
             /rosout                                                         18 msgs    : rosgraph_msgs/Log                     (9 connections)
             /rosout_agg                                                      3 msgs    : rosgraph_msgs/Log
```

The camera certainly publishes depth data:

```
strands@bobl:~$ rostopic hz /head_xtion/depth/image_raw
subscribed to [/head_xtion/depth/image_raw]
average rate: 29.933
        min: 0.031s max: 0.037s std dev: 0.00116s window: 29
```

but during record there is no `/compressed_depth` topic, but many depth compressed things:

```
strands@bobl:~$ rostopic list | grep compressed
/compressed_rgb/theora
/compressed_rgb/theora/parameter_descriptions
/compressed_rgb/theora/parameter_updates
/head_xtion/depth/image_rect/compressed
/head_xtion/depth/image_rect/compressed/parameter_descriptions
/head_xtion/depth/image_rect/compressed/parameter_updates
/head_xtion/depth/image_rect/compressedDepth
/head_xtion/depth/image_rect/compressedDepth/parameter_descriptions
/head_xtion/depth/image_rect/compressedDepth/parameter_updates
/head_xtion/depth/image_rect_meters/compressed
/head_xtion/depth/image_rect_meters/compressed/parameter_descriptions
/head_xtion/depth/image_rect_meters/compressed/parameter_updates
/head_xtion/depth/image_rect_meters/compressedDepth
/head_xtion/depth/image_rect_meters/compressedDepth/parameter_descriptions
/head_xtion/depth/image_rect_meters/compressedDepth/parameter_updates
/head_xtion/depth_registered/image_rect/compressed
/head_xtion/depth_registered/image_rect/compressed/parameter_descriptions
/head_xtion/depth_registered/image_rect/compressed/parameter_updates
/head_xtion/depth_registered/image_rect/compressedDepth
/head_xtion/depth_registered/image_rect/compressedDepth/parameter_descriptions
/head_xtion/depth_registered/image_rect/compressedDepth/parameter_updates
/head_xtion/rgb/image_color/compressed
/head_xtion/rgb/image_color/compressed/parameter_descriptions
/head_xtion/rgb/image_color/compressed/parameter_updates
/head_xtion/rgb/image_color/compressedDepth
/head_xtion/rgb/image_color/compressedDepth/parameter_descriptions
/head_xtion/rgb/image_color/compressedDepth/parameter_updates
/head_xtion/rgb/image_mono/compressed
/head_xtion/rgb/image_mono/compressed/parameter_descriptions
/head_xtion/rgb/image_mono/compressed/parameter_updates
/head_xtion/rgb/image_mono/compressedDepth
/head_xtion/rgb/image_mono/compressedDepth/parameter_descriptions
/head_xtion/rgb/image_mono/compressedDepth/parameter_updates
/head_xtion/rgb/image_rect/compressed
/head_xtion/rgb/image_rect/compressed/parameter_descriptions
/head_xtion/rgb/image_rect/compressed/parameter_updates
/head_xtion/rgb/image_rect/compressedDepth
/head_xtion/rgb/image_rect/compressedDepth/parameter_descriptions
/head_xtion/rgb/image_rect/compressedDepth/parameter_updates
/head_xtion/rgb/image_rect_color/compressed
/head_xtion/rgb/image_rect_color/compressed/parameter_descriptions
/head_xtion/rgb/image_rect_color/compressed/parameter_updates
/head_xtion/rgb/image_rect_color/compressedDepth
/head_xtion/rgb/image_rect_color/compressedDepth/parameter_descriptions
/head_xtion/rgb/image_rect_color/compressedDepth/parameter_updates

```

**Comment by nilsbore** [comment] 2015-06-18 16:57
I think it's because the recorder is subscribing to '/head_xtion/depth/image_raw' but looking at the topic list, that is not published. Which camera driver are you using?

**Comment by cburbridge** [comment] 2015-06-18 21:57
that topic is published, using openni_wrapper https://github.com/strands-project/openni_wrapper. The list above is just the topics while the record launch file is running, piped through `| grep compressed`, so you don't see the depth image. I was expecting to see some compressed depth image topic in there...

**Comment by cburbridge** [comment] 2015-08-17 14:04
Trying this again, I now get the following error when launching record.launch:

```
/opt/ros/indigo/lib/image_transport/republish: symbol lookup error: /opt/ros/indigo/lib//liblibav_image_tr
ansport.so: undefined symbol: avcodec_register_all
```

then the depth _compressor node dies. @nilsbore any idea how I can fix this?

**Comment by nilsbore** [comment] 2015-08-17 14:12
@cburbridge Sorry, I forgot about this. I will have a look now. I will try recording to a rosbag using openni_wrapper, that should replicate your setup, right?

**Comment by nilsbore** [comment] 2015-08-17 14:13
Hmm, and libav should be installed with libav_image_transport so that part is weird.

**Comment by cburbridge** [comment] 2015-08-17 14:14
when I created this issue I was using openni_wrapper, but since then I am using openni2_launch. Neither work, but since moving to openni2_launch I got:

```
strands@bob:~/chris_ws$ rosrun image_transport republish raw in:=/head_xtion/depth/image_raw libav out:=/compressed_depth
/opt/ros/indigo/lib/image_transport/republish: symbol lookup error: /opt/ros/indigo/lib//liblibav_image_transport.so: undefined symbol: avcodec_register_all
```

Not sure this is related to which openni wrapping I use though.

**Comment by nilsbore** [comment] 2015-08-17 14:24
Ok, will try with openni2 then.

**Comment by nilsbore** [comment] 2015-08-17 14:40
It seems like one issue is that openni2 is encoding the raw depth image as 32FC1 while openni_wrapper was encoding it as 16UC1. (32 bit float vs 16 bit unsigned integer). I'll see if I can get to the bottom of why you can't find the library as well.

**Comment by nilsbore** [comment] 2015-08-17 14:43
Sorry, I checked the wrong topic, it's still 16UC1, phew! Means that it should still work in theory=).

**Comment by nilsbore** [comment] 2015-08-17 22:24
There seems to be an issue with the libraries installing correctly but the installed version of libav_image_transport not linking correctly (the locally compiled version works). This was an issue before but we got it to work so there must have been a regression at some point. I'll try and find it tomorrow.

**Comment by nilsbore** [comment] 2015-08-18 13:44
@cburbridge The local build works fine already and https://github.com/strands-project/data_compression/pull/65 should fix the problem with the installed version. I'll make sure that the new version gets released soon, until then you can compile it yourself.

**Comment by nilsbore** [comment] 2015-08-21 14:18
Fixed by https://github.com/strands-project/data_compression/pull/65, closing.

**Closed as completed by nilsbore** 2015-08-21 14:18 UTC
